spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travel-together?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      springframework:
        orm:
          jpa: INFO